spring:
  datasource:
    url: jdbc:postgresql://test.elegant-designs.net:5432/shervin
    username: shervin
    password: shervin

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://test.elegant-designs.net:8761/eureka
